version: "3.9"
   
services:
  dev_container:
    build:
        context: ..
        dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - ./../.env
    volumes:
      - ~/.aws:/home/ubuntu/.aws
      - ~/.ssh:/home/ubuntu/.ssh
      - ../../:/home/ubuntu/git
      - ~/.bash_history:/home/ubuntu/.bash_history
      - ~/.mix:/home/ubuntu/.mix
    depends_on: 
      - chrome
    command: sleep infinity
    network_mode: host
 
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    hostname: chrome
    environment:
      SE_VNC_NO_PASSWORD: 1
    shm_size: 2gb
    restart: always
    ports:
      - 4444:4444
